name: Documentation
description: Report doc issues or propose improvements
labels: [documentation]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is missing, incorrect, or needs improvement?
      placeholder: The JsonDraw view is not documented in...
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Doc location
      description: File path or URL (if applicable)
      placeholder: docs/features/visualization.md or https://jsonviz.online/docs
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested changes
      description: Provide a proposed edit or outline.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, examples, or links that help clarify.
