name: Deploy 🕊️

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    name: Build & Deploy 🚀
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CHAT_API_KEY: ${{ secrets.NEXT_PUBLIC_CHAT_API_KEY }}
      NEXT_PUBLIC_CHAT_API_URL: ${{ secrets.NEXT_PUBLIC_CHAT_API_URL }}
      NEXT_PUBLIC_COLLAB_TYPE: ${{ secrets.NEXT_PUBLIC_COLLAB_TYPE }}
      NEXT_PUBLIC_DB_API_KEY: ${{ secrets.NEXT_PUBLIC_DB_API_KEY }}
      NEXT_PUBLIC_DB_APP_ID: ${{ secrets.NEXT_PUBLIC_DB_APP_ID }}
      NEXT_PUBLIC_DB_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_DB_AUTH_DOMAIN }}
      NEXT_PUBLIC_DB_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_DB_PROJECT_ID }}
      NEXT_PUBLIC_DB_SENDER_ID: ${{ secrets.NEXT_PUBLIC_DB_SENDER_ID }}
      NEXT_PUBLIC_DB_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_DB_STORAGE_BUCKET }}
      NEXT_PUBLIC_DB_URL: ${{ secrets.NEXT_PUBLIC_DB_URL }}
      NEXT_PUBLIC_DISABLE_EXTERNAL_MODE: ${{ secrets.NEXT_PUBLIC_DISABLE_EXTERNAL_MODE }}
      NEXT_PUBLIC_METERED_API_KEY: ${{ secrets.NEXT_PUBLIC_METERED_API_KEY }}
      NEXT_PUBLIC_METERED_DOMAIN: ${{ secrets.NEXT_PUBLIC_METERED_DOMAIN }}
      NEXT_PUBLIC_METERED_REGION: ${{ secrets.NEXT_PUBLIC_METERED_REGION }}
      NEXT_PUBLIC_NODE_LIMIT: ${{ secrets.NEXT_PUBLIC_NODE_LIMIT }}
      NEXT_PUBLIC_P2P_APP_ID: ${{ secrets.NEXT_PUBLIC_P2P_APP_ID }}
      NEXT_PUBLIC_P2P_OPTION: ${{ secrets.NEXT_PUBLIC_P2P_OPTION }}
      NEXT_PUBLIC_P2P_RELAY_URLS_A: ${{ secrets.NEXT_PUBLIC_P2P_RELAY_URLS_A }}
      NEXT_PUBLIC_P2P_RELAY_URLS_B: ${{ secrets.NEXT_PUBLIC_P2P_RELAY_URLS_B }}
      NEXT_PUBLIC_WS_SERVER_URL: ${{ secrets.NEXT_PUBLIC_WS_SERVER_URL }}
      NEXT_TELEMETRY_DISABLED: ${{ secrets.NEXT_TELEMETRY_DISABLED }}
      VITE_APP_LIBRARY_BACKEND: ${{ secrets.VITE_APP_LIBRARY_BACKEND }}
      VITE_APP_LIBRARY_URL: ${{ secrets.VITE_APP_LIBRARY_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build && touch ./out/.nojekyll #✎ Adjust to your build output folder (dist or out)

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          folder: out #✎ Adjust to your build output folder (dist or out)
